platforma/Controllers/ForumsController.cs
using Microsoft.Ajax.Utilities;
using platforma.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace platforma.Controllers
{
    public class ForumsController : Controller
    {
        DataContext db = new DataContext();

        // GET: Forums
        public ActionResult Index()
        {
            string query = "SELECT f.* " +
                "FROM platforma.forums f ";
            var data = db.Forums.SqlQuery(query).ToList();

            return View(data);
        }

        // GET: Forums/Details/5
        public ActionResult Details(int id)
        {
            string queryComments = "SELECT fc.* " +
                "FROM platforma.forumcomments fc " +
                "WHERE fc.forumid = @p0 " +
                "ORDER BY fc.datecomment DESC ";
            var comments = db.Comments.SqlQuery(queryComments, id).ToList();

            string query = "SELECT f.id, f.description " +
                "FROM platforma.forums f " +
                "WHERE f.id = @p0 ";
            var data = db.Forums.SqlQuery(query, id).SingleOrDefault();
            data.Comments = comments;

            return View(data);
        }

        // GET: Forums/AddComment/5
        public ActionResult AddComment(int id)
        {
            Session["forumId"] = id;
            return View();
        }

        // POST: Forums/AddComment/5
        [HttpPost]
        public ActionResult AddComment(ForumComment newComment)
        {
            try
            {
                if (Session["studentId"] != null)
                {
                    int studentId = (int)Session["studentId"];
                    int forumId = (int)Session["forumId"];
                    string queryAddComment = string.Format("CALL platforma.add_forum_comment_as_a_student({0}, {1}, \'{2}\')", forumId, studentId, newComment.Comment);
                    int output = db.Database.ExecuteSqlCommand(queryAddComment);

                }
                else
                {
                    int instructorId = (int)Session["instructorId"];
                    int forumId = (int)Session["forumId"];
                    string queryAddComment = string.Format("CALL platforma.add_forum_comment_as_an_instructor({0}, {1}, \'{2}\')", forumId, instructorId, newComment.Comment);
                    int output = db.Database.ExecuteSqlCommand(queryAddComment);
                }

                string _redirect = "Details/" + (int)Session["forumId"];
                return RedirectToAction(_redirect);
            }
            catch
            {
                return View();
            }
        }

        // GET: Forums/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Forums/Create
        [HttpPost]
        public ActionResult Create(Forum newForum)
        {
            try
            {
                string queryCreate = string.Format("CALL platforma.insert_forum(\'{0}\')", newForum.Description);
                int output = db.Database.ExecuteSqlCommand(queryCreate);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

platforma/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
       
    </style>

</head>
<body style="background: url(/Data/usblaptop_background.jpg) no-repeat fixed; background-size: 100%; font-size: 16px; font-weight: 700;">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Yo! Learn", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Categories", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Courses", "Index", "Courses")</li>
                    <li>@Html.ActionLink("Forum", "Index", "Forums")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Jovan Velkovski</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>